import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { Sparklines, SparklinesLine, SparklinesBars } from "react-sparklines";
import { useQuery, QueryClient } from "react-query";

const queryClient = new QueryClient();

export default function Home(initialData) {
	const { giphy } = initialData;
	useEffect(() => {
		console.log(initialData.giphy.data, "initialdata");
	}, []);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='stylesheet' href='/styles.css' />
			</Head>
			<h1>Welcome to Next js App</h1>
			<ul>
				{giphy.data.map((gif,index) => {
					return <li key ={index}><img src={gif.images.original.url} alt={gif.title}/></li>
				})}
			</ul>
		</div>
	);
}

// const fetchData = async () => {
// 	let res = await fetch(
// 		"https://api.giphy.com/v1/gifs/search?q=cats&api_key=nPJNlVceWHERWCSDBW5XMo1p90l7l9ie&limit=10"
// 	);
// 	res = res.json();
// 	return res;
// };

export async function getStaticProps() {
	// await queryClient.prefetchQuery("myData", fetchData);
	let giphy = await fetch(
		"https://api.giphy.com/v1/gifs/search?q=cats&api_key=nPJNlVceWHERWCSDBW5XMo1p90l7l9ie&limit=10"
	);
	giphy = await giphy.json();

	return {
		props: {
			giphy: giphy,
		},
	};
}
